source 'https://github.com/CocoaPods/Specs.git' 
platform :ios, "8.0"
use_frameworks!

target 'EspTouch_Example' do
  pod 'EspTouch', :path => '../'

  target 'EspTouch_Tests' do
    inherit! :search_paths

    
  end
end
